I submitted the Chinese version of the manual
Ultraschall/ultraschall-manual pull request #42
Opened 2024-03-26 05:31 UTC by kokdemo

cover almost post in the manual

**What does this PR do and why is it necessary?**
There are a lot of users in China who need a manual to learn

**How was it tested? How can it be tested by the reviewer?**

**Any background context you want to provide?**

**What are the relevant tickets if any?**

**Screenshots (if appropriate)**

**Further notes**

2024-04-14 11:05 UTC, Bra-Ger requested changes
I found only a few minor issues  which are caused by the retranslation into English. Please check if the translation in the Chinese version are correct.

2024-04-14 11:05 UTC, Bra-Ger commented on i18n/zh-cn/docusaurus-theme-classic/footer.json
> +    "message": "贡献者",
Translation sounds strange in English but might be correct in Chinese

2024-04-14 11:05 UTC, Bra-Ger commented on i18n/zh-cn/docusaurus-plugin-content-docs/current/Schnitt.md
> +### 双端录音
Retranslation into English is strange "Dual-Ended Recording" but the translation might be OK.

2024-04-14 11:10 UTC, nucleus-ffm requested changes
looks good, but some translations sound strange

2024-04-14 11:10 UTC, nucleus-ffm commented on i18n/zh-cn/code.json
not yet fully translated

2024-04-14 11:10 UTC, nucleus-ffm commented on i18n/zh-cn/docusaurus-plugin-content-blog/options.json
not yet fully translated

2024-04-14 11:10 UTC, nucleus-ffm commented on i18n/zh-cn/docusaurus-plugin-content-docs/current.json
> +    "message": "Next",
Missing translation

2024-04-14 11:10 UTC, nucleus-ffm commented on i18n/zh-cn/docusaurus-plugin-content-docs/current.json
> +    "message": "贡献者",
The translation says "benefactor" - is that the right translation for "contributor"?

2024-04-14 11:22 UTC, nucleus-ffm commented
Thank you for your work. We really appreciate your pull request. We have tried to review it (with a translation of course) and have noticed some strange translations. You may want to take a look at our comments and confirm that this is the correct translation. There are also some minor translations missing. 

There will also soon be the 5.1 release of Ultraschall with some minor updates to the manual [prepare 5.1](https://github.com/Ultraschall/ultraschall-manual/tree/prepare-5.1). We will merge the branch soon. It would be great if you could also update your translation then.

2024-11-17 08:50 UTC, nucleus-ffm commented
In the meantime, we merged version 5.1 into the docu. Are you interested in updating the CH version?

2024-11-17 09:24 UTC, nucleus-ffm commented
We will merge the PR into a new branch to test it. We will create a new PR to merge it into main afterwards.

2024-11-17 09:24 UTC, merged